<?php
include 'class/dbc.php';
include 'class/game.php';
include 'parts/header.php';
?>

<div class="container-fluid primary">
    <div class="row">
        <div class="col-xs-12">
            <div class="col-xs-12 np">
                <div class="card">
                    <h1>Playdek Terms of Use and Privacy Policy</h1>
                    <div class="inc-post-body">
                        <div class="inc-post-inner inc-article">
                            <div class="inc-app-page">
                                <div class="inc-app-page-title">
                                    Terms of Use and Privacy Policy
                                </div>


                                <p><strong>Playdek Terms of Use and Privacy Policy</strong><br>
                                    <strong>A<a name="Terms" id="Terms"></a>. Terms of Use</strong><br>
                                    1) <strong>INTRODUCTION</strong>. These terms  of use, as amended from time to time, are a legal agreement between Playdek,  Inc, its affiliates and any of their respective successors or assigns  (collectively, “Playdek,” “we” or “us”) and you regarding your use of Playdek’s  websites or applications created or controlled by Playdek (collectively, the  “Services”). &nbsp;The Services are offered to you by Playdek and its  development and technology partners, suppliers, service providers, licensors  and licensees (collectively, “Third Party Providers”) who may assist in the  development, hosting, operation, distribution, marketing, publication or  exploitation of the Services. &nbsp;Your access to and the use of the Services  is subject to your acceptance of the terms, conditions, policies and notices  contained herein (the “Agreement”). &nbsp;Your access to and use of the  Services constitutes your acceptance, without modification, of this Agreement  and also our&nbsp;<a href="#Privacy" title="Privacy Policy">Privacy Policy</a>.&nbsp;&nbsp;In addition, we require your express acceptance  to this Agreement and the Privacy Policy, the terms of which are incorporated  herein by reference, when you register to access and use the Services. &nbsp;If  you do not agree to be bound by this Agreement or the Privacy Policy, then you  are not permitted to register for access or use of the Services and are not to  use or access the Services.<br>
                                    2) <strong>GRANT OF LIMITED LICENSE TO  USE THE SERVICES</strong>.<br>
                                    Subject to the terms and conditions  of this Agreement, you are hereby granted a limited non-exclusive,  non-transferable, revocable license during the term of this Agreement to access  and use the Services. ALL RIGHTS NOT EXPRESSLY GRANTED IN THIS AGREEMENT ARE  RESERVED BY PLAYDEK. Playdek reserves the right to interrupt all or any aspect  of Services from time to time on a regularly scheduled basis or otherwise with  or without prior notice, for any reason (or no reason), including, without  limitation, in order to perform maintenance. You understand and agree that  delays and disruptions of other network transmissions are completely beyond our  control. You acknowledge that the Services may also be interrupted for reasons  beyond the control of Playdek and Playdek cannot guarantee that you will be  able to access the Services or your User Account (as defined below) whenever  you may wish to do so. Playdek has the right at any time for any reason or no  reason to change and/or eliminate any aspect of the Services as Playdek shall  determine at its discretion. Solely for purposes of clarity and without  limiting or waiving any term or condition set forth elsewhere in this  Agreement, we are entitled, with immediate effect, to block your access to the  Services where you use the Services in a manner that violates applicable law or  in a manner that Playdek determines is a breach of this Agreement. Your right  to access and use the Services is provided at our discretion, and your account  may be suspended or terminated at any time and for any reason. Only individuals  may apply for registration, and organizations or companies are not eligible to  register for Services without the express written permission of Playdek, which  it may withhold in its discretion.<br>
                                    3) <strong>ELIGIBILITY</strong>. You are only  eligible to register for certain Services if you meet certain requirements as  set forth at the time of registration. If you do not meet such requirements,  then you may not register for Services.<br>
                                    4) <strong>USER ACCOUNT</strong>.&nbsp;Certain  content and Services that Playdek may offer or that you may wish to access will  require that you first register with Playdek and create an account (“User  Account”), although many Services are accessible without the requirement of a  User Account.&nbsp; You must be 13 years or  older to create a User Account. &nbsp;This  Agreement applies equally to your access to and use of the Services without  establishing a User Account as well as your access to and/or use of the  Services for which a User Account is required.<br>
                                    a) <strong>Establishing  a User Account</strong>. To establish a User Account, you may be required to provide  Playdek with certain personal information, including without limitation, your  first and last name, date of birth, e-mail address, account information for  certain third party sites or networks such as Facebook or Twitter, phone  numbers (including cell phone numbers), mailing address and zip code that may  be used to identify you as an authorized user of the Service. You agree that  you will supply accurate information to Playdek when requested, and that you  will update that information promptly if it changes. Playdek reserves all  rights to pursue legal action against all persons who misrepresent personal  information or who are otherwise untruthful about their identity, and to  suspend or cancel User Accounts registered with inaccurate or incomplete  information.<br>
                                    b) <strong>Login  Information</strong> . During the registration process, you may be required to  select a username and a password (collectively, “Login Information”). It is  important that you remember your Login Information and that you keep your Login  Information in a safe and secure offline location. You may not share or  transfer your User Account or the Login Information with anyone other than as  expressly set forth in this Agreement. You are responsible for protecting the  confidentiality of the Login Information, and you will be responsible for all  use of your User Account accessed with your Login Information, whether or not  authorized by you. Any unauthorized access, use, distribution or transfer of  your User Account or Login Information may result in suspension, termination,  or cancellation of your User Account and your access to and use of the  Services.<br>
                                    c) <strong>Security  of Your User Account and Login Information</strong>. In the event that you become  aware of or suspect unauthorized use of your User Account or Login Information  or any other breach of security, you agree to immediately notify Playdek of  such use pursuant to the Notice provision below, and ensure that you secure  your User Account, Login Information and computer from unauthorized access and  use. Once we are notified of any unauthorized use or breach of security, we  will attempt to reset your Login Information, which may require you to provide  us with a new username or password. In accordance with our Privacy Policy, we  have implemented technical, administrative and physical security measures to  help safeguard and prevent unauthorized access, use or disclosure of your  personal information. Although we use reasonable efforts to safeguard the  security of your personal information, transmissions made on or through the  Internet and personal information stored on our servers or the servers of Third  Party Providers that we may use are vulnerable to attack and cannot be  guaranteed to be secure. In addition, submissions made via email are not  protected by encryption and are vulnerable to interception during transmission.  Playdek hereby disclaims any liability for security breaches, access to or  disclosure of your personal information or the unavailability of the Service or  any delay or failure to perform resulting from any causes whatsoever.<br>
                                    d) <strong>No  Ownership of Your User Account</strong>. YOU AGREE THAT YOU HAVE NO OWNERSHIP OR  OTHER PROPERTY INTEREST IN YOUR USER ACCOUNT, AND THAT ALL RIGHTS IN AND TO THE  USER ACCOUNTS ARE AND SHALL FOREVER BE OWNED BY AND INURE TO THE BENEFIT OF PLAYDEK.<br>
                                    5) <strong>CODE OF CONDUCT</strong>. Your use  of the Services is governed by certain rules (the “Code of Conduct”) maintained  and enforced by or on behalf of Playdek and to which you (and all users) must  adhere. It is your responsibility to know, understand and abide by the Code of  Conduct. The following rules are not meant to be exhaustive. In addition to the  conduct specified below, Playdek reserves the right, in its discretion, to take  disciplinary or other measures as it sees fit in response to conduct that it  deems unacceptable, including, without limitation, to delete or alter any  username or the suspension, termination, or cancellation of your User Account  and your access to and use of the Services, or terminate any license granted in  this Agreement, for any reason whatsoever. Playdek reserves the right to modify  the Code of Conduct at any time.<br>
                                    a) <strong>Unacceptable  Online Conduct.</strong> Any attempt by you to disrupt, or encourage or promote the  disruption of the Services may be a violation of criminal and civil laws. You  agree that you will not violate any applicable law, rule or regulation in  connection with your use of the Services, nor will you interrupt or attempt to  interrupt the operation of the Services in any way, including without  limitation, the following:<br>
                                    i)  use any unauthorized third-party that intercepts, or otherwise collects,  information from or through the Services;<br>
                                    ii)  modify or cause to be modified any files that are a part of the Services in any  way;<br>
                                    iii)  facilitate, create or maintain any unauthorized connection to the Services; or<br>
                                    iv)  disrupt or assist in the disruption of any computer used to support the  Services or another individual’s access to or use of the Services.<br>
                                    b) <strong>Username  Rules.</strong> Playdek may change your username, block your registration, remove  your username from all aspects the Service, and/or suspend or terminate your  access to the Service if Playdek determines, at its discretion, that your  username is contrary to the terms of this Agreement, including, without  limitation, the requirements set forth in this Section 5. You may not use any  name:<br>
                                    i)  that belongs to another person with the intent to impersonate that person or  that may mislead others to believe you to be the other person an employee of Playdek;<br>
                                    ii)  that uses vulgar or insulting language or which is otherwise offensive,  defamatory, obscene, hateful, or racially, ethnically, or religiously charged,  or other language Playdek considers objectionable;<br>
                                    iii)  that belongs to a popular culture figure, character, celebrity, media  personality or any other name protected by a third-party’s trademark(s),  service mark, publicity rights or other proprietary rights;<br>
                                    iv)  that is, contains, or is substantially similar to, a trademark or service mark,  whether registered or not; or<br>
                                    v)  that is related to drugs, sex, alcohol, or criminal activity.<br>
                                    c) <strong>Rules  Related to Use of Games, Apps and Other Content available as part of the  Services. </strong>If you download or otherwise access a game or application  (commonly known as an “app”) or any other content (collectively, “Third Party  Channels”) and breach the terms and conditions associated with the access and  use of such Third Party Channels, or otherwise use or access such game app or  content in a manner that Playdek deems inappropriate, then your User Account  may be immediately terminated or suspended.<br>
                                    6) <strong>COMMUNICATION AND OTHER  FEATURES AVAILABLE IN CONNECTION WITH GAMES, APPS AND OTHER CONTENT AVAILABLE  AS PART OF THE SERVICES</strong>.<br>
                                    a) <strong>Communication  Features</strong>. When using or accessing Third Party Channels, you understand that  you may be exposed to messages, information, data, text, software, graphic  files, advertising or other materials, whether in written, verbal, electronic,  digital, machine-readable or other form (whether now known or hereafter to  become known) from other users (“Third Party User Material”) and that you might  find such Third Party User Material objectionable. Playdek and its Third Party  Providers do not control the content of any Third Party User Material and do  not guarantee its accuracy, integrity or quality. You understand that any Third  Party User Material sent through or appearing on the Third Party Channels is the  sole responsibility of those users or persons transmitting such Third Party  User Material. This means that you, and not Playdek or its Third Party  Providers, are entirely responsible for all Third Party User Material that you  transmit or receive. Under no circumstances will Playdek or its Third Party  Providers be liable for any errors or omissions in any Third Party User  Material or for any loss or damages of any kind incurred as a result of the  access to, downloading, viewing, listening, use of or inability to use any  Third Party User Material. Playdek and its Third Party Providers have no  obligation to monitor or supervise Third Party User Material, and expressly  disclaim any representation that they will monitor or supervise such Third  Party User Material. You agree that you have no expectation of privacy in  connection with any Third Party User Material. You also agree to indemnify and  defend and hold Playdek and its Third Party Providers harmless from any claim  or demand, including reasonable attorneys’ fees, made by any third party due  to, or arising out of, your violation of these terms and conditions or your  violation of any rights of another.<br>
                                    b) <strong>Purchase  Features. </strong>Some applications offered by way of the Services or otherwise  referenced on the Playdek websitemay include the ability to make purchases  within the application itself (also referred to as “in-app purchases”). This  can include the ability to purchase additional content or access additional  features without having to leave the application. The device on which you are  accessing such applications may include settings that prevent access to certain  features or content, which may allow you to turn off the ability to make in-app  purchases. For example, Apple, Inc. outlines the steps required to enable  restrictions on certain of its devices at <a href="http://support.apple.com/kb/HT4213">http://support.apple.com/kb/HT4213</a>. Please review your settings on your device or seek advice  from your data carrier or the manufacturer of your device on how to change your  settings or enable restrictions.<br>
                                    c) <strong>Social  Network Access</strong>. When using some applications offered by way of the Services  or otherwise referenced on the Playdek website, you may have the ability to  access a social network. If you access a social network, you may need to share  information (some of which could be personally identifiable information).<br>
                                    7) <strong>OWNERSHIP</strong>. Nothing  contained in this Agreement shall be construed as conferring any license or  right, by implication, estoppel or otherwise without the written permission of Playdek.  You acknowledge that all rights, ownership, intellectual property and title in  and to the Services, including without limitation any User Accounts, Login  Information, titles, trademarks, trade names, service marks, moral rights,  computer code, themes, objects, catch phrases, locations, concepts, artwork,  animations, sounds, music, video, photographs, opinions, images, text,  audio-visual effects, or methods of operation and any documentation related to  any of the aforementioned items (collectively, “Materials”) are owned and  controlled by Playdek or its Third Party Providers. You may not use, copy,  reproduce, create derivative works from, perform, publicly display, adapt,  upload, modify, edit, publish, post, transmit, participate in the transfer or  sale, license, distribute or exploit, in any way whatsoever, the Materials  contained in the Services without the express written permission of Playdek or  its Third Party Providers. Any modification of the Materials or any portion thereof,  or unauthorized use of the Materials for any other purpose, constitutes an  infringement of Playdek’s, or its Third Party Providers’, copyrights and other  proprietary rights and, for clarity, nevertheless are created for Playdek or  its Third Party Providers’ sole and exclusive benefit, and are owned and  controlled by Playdek or its Third Party Providers.<br>
                                    Any and all material of any kind or  nature that you may submit (e.g., by uploading or transmitting) via the  Services (“User Content”) shall be deemed, and shall remain, the property of Playdek  or its Third Party Providers from the moment of creation. Accordingly, Playdek  shall exclusively own all now known or hereafter existing copyrights and all  other intellectual property rights to all User Content of every kind and  nature, in perpetuity, throughout the universe. To the extent that any of the  above may be void or unenforceable, you agree that any and all User Content is  hereby irrevocably assigned to Playdek or its Third Party Providers, together  with all intellectual property rights therein. To the extent any of the User  Content is not assignable, by submitting User Content in connection with your  access or use of the Services (whether such submission is directly to Playdek  or to a party associated or affiliated with Playdek), you expressly grant Playdek  or its Third Party Providers an exclusive, irrevocable license to, throughout  the universe and in perpetuity, use, copy, reproduce, create derivative works  from, perform, publicly display, adapt, translate, upload, modify, edit,  publish, post, transmit, participate in the transfer or sale, sublicense, distribute  or exploit, in any way or purpose whatsoever, any User Content, commercial or  otherwise, in any medium now known or hereafter devised, without compensation  or credit to the provider of the User Content. You also give up and agree to  never assert any claim that any use by Playdek or its Third Party Providers of  any Materials or User Content violates any of your rights, including but not  limited to moral rights, privacy rights, rights to publicity, proprietary or  other rights, or rights to credit for the material or ideas set forth therein.<br>
                                    You are granted a limited,  revocable, and nonexclusive right to create a hyperlink to any Playdek website  so long as the link does not portray Playdek or its products or services or  Third Party Providers in a false, misleading, derogatory, or otherwise  offensive manner. You may not use any Playdek logo or other proprietary graphic  or trademark as part of the link without express written permission.<br>
                                    8) <strong>DIGITAL MILLENNIUM COPYRIGHT  ACT.</strong><br>
                                    a) We  respect the intellectual property rights of others and request that users of  the Services respect the intellectual property rights of others as well.  Pursuant to 17 U.S.C. 512(i) of the United States Copyright Act, we will remove  any content that allegedly infringes another party’s copyright and reserve the  right to suspend, terminate, or cancel a User Account or a user’s access to and  use of the Services if a user is found to be a repeat infringer. If you believe  your work has been copied and is accessible through the Services in a way that  constitutes copyright infringement, you may notify our designated copyright  agent (specified below) in writing with the following and in the form required  by 17 U.S.C. 512 of the United States Copyright Act:<br>
                                    i)  provide your physical or electronic signature;<br>
                                    ii)  identify the copyright work that you believe is being infringed;<br>
                                    iii)  identify the item in the Services that you think is infringing your work and  include sufficient information about where the material is located on the  website;<br>
                                    iv)  provide us a way to contact you, such as your address, phone number or email  address;<br>
                                    v)  provide a statement that you believe in good faith that the item you have  identified as infringing is not authorized by the copyright owner, or its  agent, or the law; and<br>
                                    vi)  provide a statement by you, made under penalty of perjury, that the information  you provide in your notice is accurate, and that you are authorized to act on  behalf of the copyright owner whose work is being infringed.<br>
                                    b) Interim  Designation of Agent to Receive Notifications of Claimed Infringement, pursuant  to 17 U.S.C. 512(c) of the United States Copyright Act:<strong></strong><br>
                                    <strong><a href="mailto:%20%0dPlaydek">Playdek</a></strong><strong>, Inc </strong><br>
                                    <strong>Attn: Copyright </strong><br>
                                    <strong>2382 Faraday Avenue, Suite 130 </strong><br>
                                    <strong>Carlsbad, CA 92008</strong><br>
                                    <strong>760-804-9466</strong><br>
                                    <strong>Support@playdekgames.com</strong> <br>
                                    9) <strong>THIRD PARTY WEBSITES.</strong> When  accessing and using the Services, you may be directed to third party or  external websites that are not affiliated with Playdek (“Third Party  Websites”). Playdek and its Third Party Providers are not responsible for the  availability of Third Party Websites, and do not endorse, and are not  responsible or liable for any content, advertising, products, or other  materials contained on Third Party Websites. Playdek has no control over Third  Party Websites and therefore your access to any Third Party Websites is at your  own risk. Playdek and its Third Party Providers shall not be responsible or  liable, directly or indirectly, for any damage or loss caused or alleged to be  caused by or in connection with the use of, inability to use, or reliance on  any content, advertising, products, or other materials contained on Third Party  Websites. We recommend that you carefully review any terms and conditions,  privacy policies and any other legal documents that may be contained on any  Third Party Websites.<br>
                                    10) <strong>SUBMISSIONS</strong>. If you send  us creative suggestions, ideas, notes, drawings, concepts, or other information  (collectively the “Submissions”) such Submissions shall be deemed and shall  remain the property of Playdek in perpetuity. By making any Submission, the  sender automatically grants, or warrants that the owner of such material  expressly grants, Playdek the royalty-free, perpetual, irrevocable,  non-exclusive right and license to use, reproduce, modify, adapt, publish,  translate, and distribute such material (in whole or in part) throughout the  universe and/or to incorporate it in other works in any form, media or  technology now known or hereafter developed for any purpose that Playdek  chooses, whether internal, public, commercial, or otherwise, without any  compensation, credit or notice to the sender whatsoever. The sender waives all  so-called “moral rights” in all Submissions. The sender further waives the  right to make any claims against Playdek relating to unsolicited Submissions,  including, but not limited to, unfair competition, breach of implied contract  and/or breach of confidentiality.<br>
                                    11) <strong>CHANGES TO THE AGREEMENT</strong>.  Playdek reserves the right, at its discretion, to change, modify, add to,  supplement or delete any of the terms and conditions of this Agreement at  anytime, for any reason, including but not limited to, the availability of any  feature of the Services, hours of availability, content, data, software or  equipment needed to access the Services. Playdek will post a notice of such  changes on its website pursuant to the Notice provision below. If any changes  to this Agreement are unacceptable to you or cause you to no longer be in  compliance with this Agreement, you must immediately stop accessing or using  the Services. Your continued use of the Services following any notice of  revisions to this Agreement constitutes your complete and irrevocable  acceptance of any and all such changes.<br>
                                    12) <strong>NOTICE</strong>. In accordance  with provisions in this Agreement requiring Playdek give notice to you, Playdek  will do so by means of a general notice on its website, electronic mail to your  email address on record in your User Account (if you have created a User  Account), or by written communication sent by first class mail, postage  prepaid, or overnight courier to your address on record (if you have created a  User Account), the choice of which being at Playdek’s discretion. Any  provisions in this Agreement requiring you to give notice to Playdek can be  done so by means of email to: <a href="mailto:support@playdekgames.com">support@playdekgames.com</a> or by first class mail, postage prepaid, or overnight courier to:<br>
                                    <strong>Playdek, Inc </strong><br>
                                    <strong>2382 Faraday Avenue, Suite 130 </strong><br>
                                    <strong>Carlsbad, CA 92008</strong> <br>
                                    13) <strong>TERMINATION</strong>. Either Playdek  or you may terminate this Agreement and your User Account at anytime. You may  terminate this Agreement and your User Account by contacting Playdek and  deleting your User Account as set forth in the Privacy Policy and then  subsequently no longer accessing or using the Services. Playdek may terminate  this Agreement by asking you to stop using the Services, and, if necessary by  preventing your access to the Services and your User Account. Playdek shall  have the right to suspend, terminate, cancel, modify, or delete this Agreement  at any time for any reason or for no reason, with or without notice to you. IF  YOU VIOLATE ANY OF THE TERMS OR CONDITIONS OF THIS AGREEMENT, PLAYDEK RESERVES  THE RIGHT TO IMMEDIATELY SUSPEND, TERMINATE, OR CANCEL, IN ITS DISCRETION AND  WITHOUT NOTICE TO YOU, YOUR USER ACCOUNT OR ACCESS TO THE SERVICES. UPON  TERMINATION OF THIS AGREEMENT OR YOUR USER ACCOUNT, YOU WILL HAVE NO FURTHER  RIGHTS TO ACCESS OR USE THE SERVICES.<br>
                                    14) <strong>WARRANTY DISCLAIMER</strong>. THE  SERVICES ARE PROVIDED “AS IS”. NEITHER PLAYDEK, ITS THIRD PARTY PROVIDERS, NOR  ANY PERSON OR ENTITY INVOLVED IN CREATING, PRODUCING OR DISTRIBUTING ANY  MATERIALS IN THE SERVICES, THE SERVICES, OR ANY PLAYDEK PRODUCTS, NOR ANY OF  THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SHAREHOLDERS, INVESTORS,  PROFESSIONAL REPRESENTATIVES, LICENSORS, LICENSEES OR AGENTS, MAKE ANY WARRANTY  WHATSOEVER, INCLUDING WITHOUT LIMITATION, THAT THE SERVICES OR THEIR COMMUNICATION  FEATURES WILL BE UNINTERRUPTED, SECURE OR ERROR-FREE, THAT DEFECTS WILL BE  CORRECTED, OR THAT THE SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL  COMPONENTS. PLAYDEK EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,  INCLUDING WITHOUT LIMITATION THE WARRANTIES OF MERCHANTABILITY OR FITNESS FOR  ANY PARTICULAR PURPOSE OR USE, AND NON-INFRINGEMENT. PLAYDEK DOES NOT WARRANT  OR MAKE ANY REPRESENTATIONS REGARDING THE USE, VALIDITY, ACCURACY, SECURITY OR  RELIABILITY OF, OR THE RESULTS OF THE USE OF, OR OTHERWISE RESPECTING, THE  MATERIALS IN THE SERVICES OR ANY CONTENT, MATERIALS OR SERVICES ON ANY THIRD  PARTY WEBSITES. THIS SECTION 14 SHALL SURVIVE ANY EXPIRATION, TERMINATION OR  CANCELLATION OF THE SERVICES AND/OR THIS AGREEMENT OR ANY DETERMINATION THAT  THIS AGREEMENT OR ANY PORTION OF THIS AGREEMENT IS VOID OR VOIDABLE.<br>
                                    15) <strong>LIMITATION OF LIABILITY</strong>.  NEITHER PLAYDEK, ITS THIRD PARTY PROVIDERS, NOR ANY PERSON OR ENTITY INVOLVED  IN CREATING, PRODUCING OR DISTRIBUTING THE MATERIALS OR THE SERVICES OR ANY PLAYDEK  PRODUCTS, NOR ANY OF THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES,  SHAREHOLDERS, INVESTORS, PROFESSIONAL REPRESENTATIVES, LICENSORS, LICENSEES OR  AGENTS, SHALL BE LIABLE IN ANY WAY FOR DAMAGE OR LOSS OF ANY KIND, WHETHER FOR  BREACH OF CONTRACT, TORTIOUS BEHAVIOR, NEGLIGENCE OR ANY OTHER CAUSE OF ACTION  (EVEN IF PLAYDEK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE) RESULTING  FROM (A) THE USE OF OR INABILITY TO USE THE SERVICES; (B) THE BREACH OF ANY  REPRESENTATION OR WARRANTY (OTHER THAN THE LIMITED PRODUCT WARRANTY SET FORTH  IN PARAGRAPH 8, ABOVE); (C) THE DOWNLOADING OF ANY SOFTWARE OWNED OR OPERATED  BY PLAYDEK OR ANY THIRD PARTY PROVIDER; (D) PERSONAL INJURY OR PROPERTY DAMAGE  OF ANY NATURE WHATSOEVER RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES  OR ANY PLAYDEK PRODUCT; OR (E) INTERRUPTIONS OF SERVICE INCLUDING WITHOUT  LIMITATION INTERNET SERVICE DISRUPTIONS, SOFTWARE OR HARDWARE FAILURES OR ANY  OTHER EVENT WHICH MAY RESULT IN A LOSS OF DATA OR DISRUPTION OF SERVICE.<br>
                                    IN NO EVENT SHALL PLAYDEK, ITS THIRD  PARTY PROVIDERS, OR ANY PERSON OR ENTITY INVOLVED IN CREATING, PRODUCING OR  DISTRIBUTING THE MATERIALS, THE SERVICES, OR ANY PLAYDEK PRODUCTS, OR ANY OF  THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SHAREHOLDERS, INVESTORS,  PROFESSIONAL REPRESENTATIVES, LICENSORS, LICENSEES OR AGENTS, BE LIABLE TO YOU  OR ANYONE ELSE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL  OR ANY OTHER DAMAGES RESULTING FROM THE USE OF OR INABILITY TO USE THE  SERVICES. PLAYDEK DOES NOT WARRANT THAT YOU WILL BE FREE FROM THE BEHAVIOR OF  OTHERS YOU MAY DEEM INSULTING, DEMEANING, OFFENSIVE, THREATENING, OBSCENE,  LIBELOUS, DEROGATORY OR HARASSING WHILE ACCESSING OR USING THE SERVICES. IN THE  EVENT PLAYDEK CHOOSES NOT TO TAKE ANY ACTION, TAKES AN ACTION WITH WHICH YOU DO  NOT AGREE OR IS UNABLE TO TAKE ANY ACTION FOR ANY REASON WHATSOEVER, IN NO  EVENT SHALL PLAYDEK ITS THIRD PARTY PROVIDERS, OR ANY PERSON OR ENTITY INVOLVED  IN CREATING, PRODUCING OR DISTRIBUTING ANY MATERIALS IN THE SERVICES, OR ANY OF  THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, SHAREHOLDERS, INVESTORS,  PROFESSIONAL REPRESENTATIVES, LICENSORS, LICENSEES OR AGENTS, BE LIABLE TO YOU OR  TO ANY THIRD PARTY FOR ANY INCIDENTAL OR CONSEQUENTIAL DAMAGES, OR EMOTIONAL  DISTRESS, OR OTHER DAMAGES, ARISING OUT OF OR IN CONNECTION WITH YOUR USER  ACCOUNT OR YOUR ACCESS TO AND USE OF THE SERVICES.<br>
                                    SOME JURISDICTIONS MAY NOT ALLOW THE  LIMITATION OR EXCLUSION OF CERTAIN WARRANTIES OR DISCLAIMERS IN WHICH CASE SOME  OF THE WARRANTIES OR DISCLAIMERS PROVIDED IN THIS AGREEMENT MAY NOT BE  APPLICABLE. TO THE EXTENT THAT THE LIMITATION OF LIABILITY SET FORTH IN THIS  SECTION IS PROHIBITED OR FAILS OF ITS ESSENTIAL PURPOSE, PLAYDEK’S TOTAL  LIABILITY ARISING FROM THIS AGREEMENT AND SOLE OBLIGATION WITH RESPECT TO  DAMAGES SHALL NOT EXCEED ONE HUNDRED UNITED STATES DOLLARS (US$100.00). THIS  SECTION 15 SHALL SURVIVE ANY EXPIRATION, TERMINATION OR CANCELLATION OF THE  SERVICES AND/OR THIS AGREEMENT OR ANY DETERMINATION THAT THIS AGREEMENT OR ANY  PORTION OF THIS AGREEMENT IS VOID OR VOIDABLE.<br>
                                    16) <strong>FORCE MAJEURE</strong>. Playdek  shall not be liable for any delay or failure to perform resulting from causes  outside the reasonable control of Playdek, including without limitation, any  failure to perform hereunder due to unforeseen circumstances, such as acts of  God, war, terrorism, riots, embargoes, acts of civil or military authorities,  fire, floods, earthquakes, tornados, hurricanes, pandemics, accidents, strikes,  internet interruption, denial of service attack, hacking or shortages of  transportation facilities, fuel, energy, labor or materials.<br>
                                    17) <strong>CONSENT TO MONITOR</strong>. In  accordance with the terms and conditions of this Agreement and our Privacy  Policy, and for purposes of monitoring and improving our quality of service,  identifying Unauthorized Third Party Programs (as defined herein) and enforcing  the terms and conditions of this Agreement, you hereby acknowledge and agree  that:<br>
                                    a)When you  access and use the Services, we may obtain certain information about your  computer and its operating system, including but not limited to your IP  address(es), browser and browser version, screen resolution, and operating  system(s), for purposes of improving the Services, and to enforce the  provisions of this Agreement.<br>
                                    b)We may,  with or without notice to you, disclose your Internet Protocol (IP) address,  personal information, and other information about you and your activities (i)  in response to a request by law enforcement, a court order or other legal  process or (ii) if we believe that doing so may protect your safety or the  safety of others.<br>
                                    c) Our  websites use Google Analytics, a web analytics service provided by Google, Inc.  (“Google”). Google Analytics uses “cookies”, which are text files placed on  your computer, to help us analyze how visitors use the Services. The  information generated by the cookie about your use of our Services will be  transmitted to and stored on Google servers and may be accessed by us. Google  uses this information to help us evaluate how our websites are used. Google may  also transfer this information to third parties where required to do so by law,  or where such third parties process the information on Google’s behalf. By  using this website, you consent to the processing of data about you by Google  in the manner and for the purposes set out above. Third party sites and  services you access through our Services may also employ cookies.<br>
                                    18) <strong>NON-U.S. RESIDENTS</strong>. The  Services are controlled and operated by Playdek from its offices within the  State of California, United States of America. Playdek makes no representation  that the Materials or Services are appropriate or available for use in other  locations. Those who choose to access the Services from other locations do so  at their own initiative and are responsible for compliance with local laws, if  and to the extent local laws are applicable, and payment of any applicable  internet fees or fees charged by an internet service provider. Software from  the Services is further subject to United States export controls. No software  from the Services may be downloaded or otherwise exported or re-exported (i)  into (or to a national or resident of) Cuba, North Korea, Iran, Syria, Sudan, or  any other country to which the U.S. has embargoed goods or that has been  designated by the U.S. Government as a “terrorist supporting” country; or (ii)  to anyone on the U.S. Treasury Department’s list of Specially Designated  Nationals or the U.S. Commerce Department’s Table of Deny Orders. By using the  Services, you represent and warrant that you are not located in, under the  control of, or a national or resident of any such country or on any such list.<br>
                                    19) <strong>INDEMNITY</strong>. You agree to  indemnify, defend and hold Playdek, its Third Party Providers, or any person or  entity involved in creating, producing, or distributing any Materials or the  Services, or any of their respective directors, officers, employees or agents,  harmless from and against any and all damages, costs, losses and expenses,  including reasonable attorney fees and court costs relating to or arising  directly or indirectly from any suit, claim, demand or settlement based upon  your posting or uploading any content using any Communication Feature or your  failure to comply with this Agreement or your violation of any third party  right or your violation of any law, rule or regulation of the United States or  any other country.<br>
                                    20) <strong>INJUNCTIVE RELIEF</strong>. You  agree that a breach of this Agreement will cause irreparable injury to Playdek  and/or its Third Party Providers for which monetary damages would not be an  adequate remedy. Accordingly, Playdek shall be entitled to seek and obtain  equitable relief, including, without limitation, injunctive relief, in addition  to any other remedy to which it may be entitled under this Agreement or  applicable law, without the need to post bond or other form of security, or  provide proof of damages.<br>
                                    21) <strong>DISPUTE RESOLUTION AND  GOVERNING LAW</strong><br>
                                    a) <strong>Informal  Resolution.</strong> To expedite resolution and control the cost of any dispute,  controversy or claim related to this Agreement or the <a href="#Privacy" title="Privacy Policy">Privacy Policy</a> (“Dispute”), you and Playdek agree to first attempt to  negotiate any Dispute (except those Disputes expressly provided below)  informally for at least thirty (30) days prior to initiating any arbitration or  court proceeding. Such informal negotiations commence upon written notice from  one person or entity to the other in accordance with the Notice section above.<br>
                                    b) <strong>Binding  Arbitration</strong>. If you and Playdek are unable to resolve a Dispute through  informal negotiations, either you or Playdek may elect to have the Dispute  (except those Disputes expressly excluded below) finally and exclusively  resolved by binding arbitration. Any election to arbitrate by one party shall  be final and binding on the other. The arbitration shall be commenced and  conducted under the Commercial Arbitration Rules of the American Arbitration  Association (“AAA”) and, where appropriate, the AAA’s Supplementary Procedures  for Consumer Related Disputes (“AAA Consumer Rules”), both of which are  available at the AAA website www.adr.org. The determination of whether a  Dispute is subject to arbitration shall be governed by the Federal Arbitration  Act and determined by a court rather than an arbitrator. Your arbitration fees  and your share of arbitrator compensation shall be governed by the AAA Rules  and, where appropriate, limited by the AAA Consumer Rules. The arbitration may  be conducted in person, through the submission of documents, by phone or  online. The arbitrator will make a decision in writing, but need not provide a  statement of reasons unless requested by a party. The arbitrator must follow  applicable law, and any award may be challenged if the arbitrator fails to do  so. Except as otherwise provided in this Agreement, you and Playdek may  litigate in court to compel arbitration, stay proceeding pending arbitration,  or to confirm, modify, vacate or enter judgment on the award entered by the  arbitrator.&nbsp;The arbitration, or any action to enforce this Agreement or  the Privacy Policy may not be combined or joined with any other action or be  part of a class action.<br>
                                    <strong>THE PARTIES HEREBY WAIVE THEIR RIGHT  TO JURY TRIAL WITH RESPECT TO ALL CLAIMS AND ISSUES ARISING UNDER, IN  CONNECTION WITH, TOUCHING UPON OR RELATING TO THIS AGREEMENT, THE BREACH  THEREOF AND/OR THE SCOPE OF THE PROVISIONS OF THIS SECTION, WHETHER SOUNDING IN  CONTRACT OR TORT, AND INCLUDING ANY CLAIM FOR FRAUDULENT INDUCEMENT THEREOF.  YOU UNDERSTAND THAT, ABSENT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN  COURT AND HAVE A JURY TRIAL.</strong> <br>
                                    c) <strong>Restrictions.</strong> You and Playdek agree that any arbitration shall be limited to the Dispute  between Playdek and you individually. To the full extent permitted by law, (i)  no arbitration shall be joined with any other; (ii) there is no right or  authority for any Dispute to be arbitrated on a class-action basis or to  utilize class action procedures; and (iii) there is no right or authority for  any Dispute to be brought in a purported representative capacity on behalf of  the general public or any other persons.<br>
                                    d) <strong>Exceptions  to Informal Resolution and Binding Arbitration.</strong> You agree that Playdek may  chose, at its option and discretion, to exclude the following Disputes from  (and, as such, the following Disputes will not be subject to) the above  provisions concerning informal resolutions and binding arbitration: (i) any  Dispute related to or arising from allegations of theft, piracy, invasion of  privacy or the unauthorized use of Playdek’s or its Third Party Providers’  intellectual property and/or intellectual property rights; and/or (ii) any  claim by Playdek for injunctive or other equitable relief.<br>
                                    e) <strong>Location  and Jurisdiction. </strong>Any arbitration will be initiated in and take place in  the County of San Diego, State of California, United States of America. Any  Dispute not subject to arbitration (other than claims proceeding in any small  claims court), or where no election to arbitrate has been made, including  without limitation the Disputes contained in Section 21(d), shall be decided by  a court of competent jurisdiction wherever located, including, without  limitation, in the County of San Diego, State of California, United States of  America, and you and Playdek agree to submit to the personal jurisdiction of  such courts.<br>
                                    f) <strong>Governing  Law.</strong> Except as expressly provided otherwise, this Agreement shall be  governed by, and will be construed and enforced under, the laws, rules and  regulations of the United States of America and the laws, rules and regulations  of the State of California, excluding conflict of law rules and principles.<br>
                                    g) <strong>Severability. </strong>You and Playdek agree that if any portion of this Section 21 (Dispute  Resolution and Governing Law) is found illegal or unenforceable (with the  exception of 21(d)), that portion shall be severed and the remainder of this  section shall be given full force and effect. If Section 21(d) is found to be  illegal or unenforceable then neither you nor Playdek will elect to arbitrate  any Dispute falling within that portion of Section 21(d) found to be illegal or  unenforceable and such Dispute shall be decided by a court of competent  jurisdiction within the County of San Francisco, State of California, United  States of America, and you and Playdek agree to submit to the personal  jurisdiction of that court.<br>
                                    22) <strong>MISCELLANEOUS</strong>.  Notwithstanding Section 21(g), if any other provision of this Agreement shall  be held invalid or unenforceable, in whole or in part, such provision shall be  deemed severable from this Agreement, and the validity and enforceability of  all other provisions of this Agreement shall not be affected thereby. This  Agreement constitutes the entire agreement between the parties hereto relating  to the subject matter hereof and supersedes all prior oral and written and all  contemporaneous oral negotiations, commitments and understandings of the  parties. Sections 6, 7, 9, 11, 12, 13, 14, 17, 18, 19, 20, 21 and 22 shall  survive the expiration, termination or cancellation of the Services and/or this  Agreement or any determination that this Agreement or any portion of this  Agreement is void or voidable. You may not assign or transfer this Agreement or  your rights hereunder, and any attempt to the contrary is void. This Agreement  may only be modified as set forth herein. The section headings used herein are  for reference only and shall not be read to have any legal effect.<br>
                                    Last updated: May 1, 2013</p>
                                <div align="center">
                                    <hr size="2" width="100%" align="center">
                                </div>
                                <p><strong><a name="Privacy" id="Privacy"></a>B.  Privacy Policy</strong><br>
                                    Playdek, Inc. (“Playdek”) is  committed to safeguarding consumer privacy on the Internet and protecting the  information that you may provide to us. This document (“Privacy Policy“)  discloses the privacy practices with respect to your access and use of our  services, whether through our website www.playdekgames.com or Playdek’s mobile  applications created or controlled by Playdek (collectively, the “Services”).  Your use of the Services constitutes acceptance of both this Privacy Policy and  our&nbsp;<a href="#Terms" title="Terms of Use">Terms of Use</a>.<br>
                                    This Privacy Policy is intended to  provide you with notice of the following:</p>
                                <ol start="1" type="1">
                                    <li>What personally identifiable information is collected       and how it is collected.</li>
                                    <li>Information on the use of cookies.</li>
                                    <li>Our policies concerning children’s personally       identifiable information.</li>
                                    <li>How personally identifiable information that we collect       is used.</li>
                                    <li>With whom personally identifiable information may be       shared.</li>
                                    <li>What choices are available to you regarding the use of       your personally identifiable information.</li>
                                    <li>The security procedures in place to protect the misuse       of your personally identifiable information.</li>
                                    <li>Links to other websites and inapplicability of our       Privacy Policy.</li>
                                    <li>How you can ask questions, or send us comments, about       this Privacy Policy.</li>
                                    <li>California residents.</li>
                                    <li>Notice of change to the Privacy Policy.</li>
                                </ol>
                                <p>Please be sure to read this Privacy  Policy before using the Services or submitting information to us. This Privacy  Policy may change from time to time and your continued use of the Services  constitutes acceptance of such changes, so please check this Privacy Policy periodically  for updates. The terms and conditions of the Terms of Use are incorporated  herein by reference (and to the extent of any inconsistency between the Terms  of Use and this Privacy Policy, this Privacy Policy shall govern).<br>
                                    <strong>What  Personally Identifiable Information Is Collected and How It is Collected</strong><br>
                                    Personally identifiable information,  or personal information, is information that identifies you and may be used to  contact you either online or offline. Playdek collects personal information  when you register and create a user account in order to access certain content  and/or utilize aspects of the Services. Playdek may also collect personally  identifiable information during the course of your use of the Services and/or  in connection with marketing or email campaigns. We do not require, as a  condition of participation in any of our Services, that anyone disclose more  information than is reasonably necessary for them to participate in an  activity.<br>
                                    The type of personally identifiable  information collected will vary depending upon the activity and may include  your first and last name; e-mail address; account information for certain third  party third party sites or networks, such as Facebook and Twitter, phone  numbers; mailing address; and zip code. We will also collect the contact  information of your friends, if you choose to connect your contacts and address  book information with Playdek, and/or if you choose to connect those accounts  with your Playdek account your login credentials to your social network accounts,  such as Facebook and Twitter.<br>
                                    We also may automatically collect  certain information when you use our Services, such as your location/GPS  coordinates (if you enable this feature), a device identifier (but not the  UDID), MAC address, Internet Protocol (IP) address (if using a browser),  operating system, computer type, software, Internet IP address, the browser  type, the address of a referring site and your activity on Playdek. You can  enable or disable location services when you use Playdek at anytime, through  your mobile device settings. This information is not treated as personal  information unless we combine it with or link it to any of the personally  identifiable information mentioned above.<br>
                                    At any time, but only once per  calendar year, or as otherwise required under applicable law, you may contact Playdek  to review the personally identifiable information that Playdek has collected  about you. If you discover any errors, please notify Playdek and the  information will be corrected. To review the personally identifiable  information that Playdek has collected about you, send an email to&nbsp;<a href="mailto:support@playdekgames.com">support@playdekgames.com</a>&nbsp;with the subject line: “Personal Information Review  Request.”<br>
                                    <strong>Cookies</strong><br>
                                    We use “cookies” on Playdek’s website.  A cookie is a piece of data stored on a website visitor’s hard drive to help us  improve your access to our website and identify repeat visitors to our website.  For instance, when we use a cookie to identify you, you would not have to log  in a password more than once, thereby saving time while on our website. Cookies  can also enable us to track and target the interests of our users to enhance  the experience on our website. Usage of a cookie is not linked to any  personally identifiable information on our website.<br>
                                    <strong>Children</strong><br>
                                    We do not knowingly collect  personally identifiable information from someone we know to be a child under  the age of thirteen (13) without prior parental consent. Our websites and  application contain features that may be attractive to children; therefore,  children should not be granted access to any passwords or use of the parent or  guardian’s account without direct monitoring and supervision by the parent or  guardian. Playdek is not responsible for any unauthorized use of accounts, and  we encourage everyone to protect their passwords and not disclose them to  anyone.<br>
                                    <strong>How Personally Identifiable Information is Used</strong><br>
                                    We will only collect information to  the extent necessary for us to provide our Services. We will also use  personally identifiable information to: provide you with any information or  material you may request from us and to process or complete any transactions;  respond to your e-mails, questions or comments; analyze usage and trends and  personalize and improve Playdek and your experience when you use our Services  such as suggesting content or features that may match your interests and level  of gaming experience; send you confirmations, updates, security alerts and  support messages; find and connect with your friends and contacts (with your  permission); pair you with a user of our mobile applications who has first  provided your personally identifiable information (e-mail address) in order to  be paired with you in connection with using our mobile applications; alert you  of new products, promotions, special events and offers; and, for any other  purpose for which the personally identifiable information was collected. We may  also use personally identifiable information to allow us to deliver messages to  your personal accounts on certain third party sites or networks, such as  Facebook and Twitter. We may also need to use your personally identifiable  information to (1) respond to subpoenas or court orders, (2) to establish or  exercise our legal rights or defend against legal claims, (3) protect the  safety or property of our employees, contractors, customers, users or others or  (4) to the extent otherwise required by applicable law.<br>
                                    If at any time you wish to opt-out  from having your personally identifiable information used in order to deliver  information from Playdek about new products, services, or promotions, you may  contact us at&nbsp;<a href="mailto:support@playdekgames.com">support@playdekgames.com</a>&nbsp;with  the words “Opt Out” in the subject line of your email.<br>
                                    <strong>Sharing,  Selling or Renting of Information</strong><br>
                                    Except as described in this Privacy  Policy, we do not sell, rent, or give any retained customer information to  third parties outside of what is necessary to provide the Services. Such third  parties have access to personally identifiable information needed to perform  their functions, but may not use it for other purposes. Included among the  personally identifiable information that we may share with third parties in  connection with providing the Services are email addresses and/or certain other  personally identifiable information that we may share with our Third Party  Providers (as defined in the Terms of Use).&nbsp;We may also share personally  identifiable information with the following: with your friends with whom you  want to share information related to your use of an Playdek mobile application  or product, including messages or communications regarding your use of a mobile  application, subject to the preferences you have set for such sharing; certain  social networking services, if you have allowed such sharing to occur; to third  party users of mobile applications who have provided your personally  identifiable information (such as your &nbsp;when you have first given us your  consent to share personally identifiable information.<br>
                                    We may also disclose personally  identifiable information to third parties in order to comply with the law or  requests by law enforcement agencies, to enforce our Terms of Use, or to  protect the rights, property or safety of our website, users of our website and  others. We may also share with third parties general information that does not  include personally identifiable information, such as demographic, analytical or  aggregated non-personally identifiable information.<br>
                                    In the event we are acquired by or  merged with another company we may transfer your personally identifiable  information to the new company.<br>
                                    <strong>Your  Access to and Control Over Your Personally Identifiable Information</strong><br>
                                    You may request that we delete your  user account(s) or, if you have not established a user account, your email address,  and any related data at any time. If you wish to delete your user account(s),  please email us at support@playdekgames.com with the words “Delete Account” in  the subject line. If you do not have a user account and wish to delete your  email address or other personally identifiable information that you might have  provided through your use of the Services, please email us at&nbsp;<a href="mailto:support@playdekgames.com">support@playdekgames.com</a>&nbsp;with the words “Delete My Information” in the subject  line.<br>
                                    <strong>How  Your Personally Identifiable Information Is Protected</strong><br>
                                    The security of your personally  identifiable information is important to us. We have implemented technical,  administrative and physical security measures to attempt to protect your  personally identifiable information from unauthorized access and improper use.  However, please understand that no security measure is perfect or impenetrable  and therefore we cannot guarantee the absolute security of your personally  identifiable information.<br>
                                    We also protect your personally  identifiable information offline. Only employees who need the information to  perform a specific job (for example, customer service) are granted access to  personally identifiable information. The computers/servers in which we store  personally identifiable information are kept in a secure environment.<br>
                                    <strong>Links</strong><br>
                                    Playdek’s websites may contain links  to other websites. Please be aware that we are not responsible for the content  or privacy practices of such other websites. This Privacy Policy does not apply  to third party websites and we encourage our users to be aware when they leave  our websites and to read the privacy statements of any other website that  collects personally identifiable information since your rights will be governed  by those third party policies (and not by this Privacy Policy or Playdek).<br>
                                    <strong>How  You Can Ask Questions or Send Us Comments About This Privacy Policy</strong><br>
                                    Playdek welcomes your comments  regarding this privacy policy. If you have questions about this policy or have  technical or general support questions, please contact us at <a href="mailto:support@playdekgames.com">support@playdekgames.com</a>. You may also write to us at:<br>
                                    <strong>Playdek, Inc.<br>
                                        Attn: Policy<br>
                                    </strong><br>
                                    <strong>Playdek, Inc.</strong><br>
                                    <strong>2382 Faraday Avenue, Suite 130 </strong><br>
                                    <strong>Carlsbad CA 92008</strong><br>
                                    <strong>YOUR  CALIFORNIA PRIVACY RIGHTS</strong><br>
                                    Beginning on January 1, 2005,  California Civil Code Section 1798.83 permits California residents to request  from companies conducting business in California a list of third parties to  which the company has disclosed personally identifiable information during the  preceding year for direct marketing purposes. Playdek has not and will not  share your personally identifiable information with third parties for their  direct marketing purposes; accordingly, it will not maintain such a list of  third parties. If you are a resident of California and want additional  information confirming how Playdek does not share your personally identifiable  information with third parties for their direct marketing purposes, you may  contact us at&nbsp;<a href="mailto:support@fingerprintplay.com?subject=California%20Privacy">contact@playdekgames.com</a>&nbsp;with the words “California Privacy” in the subject  line of your email.<br>
                                    <strong>Notice  of Changes to this Privacy Policy</strong><br>
                                    We may change this Privacy Policy at  any time by posting a notice of the change. All changes will be effective when  posted.<br>
                                    Last Updated: May 1, 2013</p>

                                <div class="cleared"></div>
                            </div>
                        </div>
                    </div><!-- end  copypasta--->
                </div>
            </div>
        </div>
    </div>
</div>

<?php
include 'parts/footer.php';